### ISSUE TITLE
Birdtray unable to start thunderbird

### ISSUE THREAD

**Issue by daffamumtaz2361** [flathub/com.ulduzsoft.Birdtray#1]
**OS**: KDE Neon 5.19
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.10.0
**Birdtray origin**: Flatpak

**Description**
I enabled Start thunderbird when Birdtray starts and Restart thunderbird if it was closed option and thunderbird just won't start. I added 2 second delay and checked both hide option. Both thunderbird and birdtray is installed from flatpak.

**Expected behavior**
Thunderbird is not started at all

**To Reproduce**
1. Start birdtray, and thunderbird won't start as well
2. Manually start thunderbird
3. Close thunderbird
4. Thunderbird is not restarted

**Screenshot**
![image](https://user-images.githubusercontent.com/37852137/86884358-a71b0680-c11d-11ea-99e1-663932c9845b.png)

**Additional context**
On the debug log, this repeats until thunderbird is manually started
```
2020-07-08 13:05:02 Window ID found: 0 
2020-07-08 13:05:02 Starting Thunderbird as '/usr/bin/flatpak-spawn --host org.mozilla.Thunderbird' 
2020-07-08 13:05:03 Window ID found: 0 
2020-07-08 13:05:03 Starting Thunderbird as '/usr/bin/flatpak-spawn --host org.mozilla.Thunderbird' 
2020-07-08 13:05:04 Window ID found: 0
2020-07-08 13:05:04 Starting Thunderbird as '/usr/bin/flatpak-spawn --host org.mozilla.Thunderbird'
```

Moved from https://github.com/gyunaev/birdtray/issues/389

**Comment by daffamumtaz2361** [comment]
Fixed by simply changing thunderbird command line to `/usr/bin/flatpak-spawn --host flatpak run org.mozilla.Thunderbird`. This should be changed in the default setting

**Comment by geekley** [comment]
I suggest to change the message in flathub page to explain how to use this with non-flatpak Thunderbird:

https://github.com/flathub/com.ulduzsoft.Birdtray/blob/6cfb163f90cabec5a1dd99f753b3a1cc0f0830a9/appdata.patch#L7-L9
```html
<p>
  The feature to "Start Thunderbird when Birdtray starts" needs the flathub Thunderbird installed by default.
  The default Thunderbird directory is "~/.var/app/org.mozilla.Thunderbird/.thunderbird".<br/>
  To use non-flatpak Thunderbird, you can change a setting and load it with flatpak-spawn, e.g.:
  <br/><code>/usr/bin/flatpak-spawn --host thunderbird</code>
</p>
```
